- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: deb http://pkg.jenkins.io/debian-stable binary/
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install AWS CLI
  apt:
    name: awscli
    state: present

- name: Start and enable Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Ensure Docker is running
  systemd:
    name: docker
    state: started
    enabled: yes