- hosts: web
  become: yes
  tasks:
    - name: Remove old container
      shell: docker rm -f react-container || true

    - name: Pull latest image
      shell: docker pull omwarkri123/react-app:latest

    - name: Run container
      shell: docker run -d -p 80:80 --name react-container omwarkri/react-app:latest